# Generated by Django 6.0.5 on 2026-05-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_specialisationchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media_type',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='media_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='message',
            name='encrypted_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
